### ISSUE TITLE
Different App 

### ISSUE THREAD

**Issue by Elqul** [bcylin/Try-tvOS#1]
is this the source code for https://itunes.apple.com/tw/app/ai-liao-li/id554065086 ?
it seems like this repo is not the source code for this ios app.

**Comment by bcylin** [comment]
This repo is a tvOS app, not an iOS app.

However, it is [bundled](https://developer.apple.com/support/universal-purchase/) with the iOS app https://itunes.apple.com/tw/app/ai-liao-li/id554065086 in the App Store. They are different apps sharing the same title.
